'use client';
import {useState,useEffect,useRef} from 'react';
import {Crown,Volume2,VolumeX,Settings2,HelpCircle,ArrowRight,RotateCcw,Users,Bot,X,Trophy,ChevronDown,Home,Flag,ShieldCheck,Sparkles} from 'lucide-react';
import {PATH,SAFE,HOME,coordinate,legal,advance} from '../lib/engine.mjs';
const COLORS=['#ed514e','#37b77f','#f4c44d','#498fe9'];
const NAMES=['Rouge','Vert','Jaune','Bleu'];
const DOTS:Record<number,number[]>={1:[4],2:[0,8],3:[0,4,8],4:[0,2,6,8],5:[0,2,4,6,8],6:[0,2,3,5,6,8]};
const fresh=()=>Array.from({length:4},()=>[-1,-1,-1,-1]);
export default function Game(){
 const [tokens,setTokens]=useState<number[][]>(fresh),[active,setActive]=useState([0,2]),[turn,setTurn]=useState(0),[dice,setDice]=useState(1),[phase,setPhase]=useState('roll'),[mode,setMode]=useState('bot'),[draftMode,setDraftMode]=useState('bot'),[count,setCount]=useState(2),[modal,setModal]=useState(''),[sound,setSound]=useState(true),[rolling,setRolling]=useState(false),[message,setMessage]=useState('À vous de lancer le dé !'),[logs,setLogs]=useState<string[]>([]),[winner,setWinner]=useState<number|null>(null),[sixes,setSixes]=useState(0),[moves,setMoves]=useState(0),[fast,setFast]=useState(false);
 const audio=useRef<AudioContext|null>(null),lock=useRef(false),epoch=useRef(0);
 useEffect(()=>{if(!modal)return;const previous=document.activeElement as HTMLElement;const dialog=document.querySelector('[role="dialog"]') as HTMLElement;const focusable=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button,input,select,[tabindex="0"]')||[]);focusable()[0]?.focus();const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')setModal('');if(e.key==='Tab'){const items=focusable();const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);previous?.focus()};},[modal]);
 const computer=mode==='bot'&&turn!==0;
 const options=phase==='choose'?legal(tokens,turn,dice):[];
 function tone(freq=440,duration=.1){if(!sound)return;try{audio.current??=new AudioContext();void audio.current.resume();const a=audio.current,o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.075,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+duration);o.start();o.stop(a.currentTime+duration);}catch{}}
 function nextTurn(){setTurn(t=>active[(active.indexOf(t)+1)%active.length]);setPhase('roll');setSixes(0);setMessage('Lancez le dé pour avancer.');}
 const pause=(ms:number)=>new Promise(r=>setTimeout(r,ms));
 async function roll(){if(lock.current||phase!=='roll'||winner!==null||modal)return;lock.current=true;const e=epoch.current;setRolling(true);setPhase('rolling');for(let j=0;j<9;j++){if(e!==epoch.current)return;setDice(1+Math.floor(Math.random()*6));tone(260+j*35,.045);await pause(fast?30:65);}if(e!==epoch.current)return;const value=crypto.getRandomValues(new Uint32Array(1))[0];const d=value>=4294967292?1+Math.floor(Math.random()*6):1+value%6;setDice(d);setRolling(false);tone(600,.15);if(d===6&&sixes===2){setMessage('Trois 6 consécutifs : tour terminé.');setPhase('waiting');await pause(1000);if(e!==epoch.current)return;nextTurn();}else if(legal(tokens,turn,d).length){setSixes(s=>d===6?s+1:0);setMessage(d===6?'Un 6 ! Sortez un pion ou avancez.':'Choisissez un pion à déplacer.');setPhase('choose');}else{setMessage('Aucun déplacement possible.');setPhase('waiting');await pause(950);if(e!==epoch.current)return;nextTurn();}lock.current=false;}
 async function move(i:number){if(lock.current||phase!=='choose'||!options.includes(i)||winner!==null)return;lock.current=true;const e=epoch.current;setPhase('moving');const from=tokens[turn][i];const result=advance(tokens,turn,i,dice);for(let p=from<0?0:from+1;p<=result.tokens[turn][i];p++){if(e!==epoch.current)return;setTokens(prev=>prev.map((a,c)=>a.map((v,j)=>c===turn&&j===i?p:v)));tone(350+p*7,.055);await pause(fast?50:130);}if(e!==epoch.current)return;setTokens(result.tokens);setMoves(m=>m+1);const line=result.captured?`${NAMES[turn]} capture ${result.captured} pion${result.captured>1?'s':''} !`:result.finished?`${NAMES[turn]} : un pion à l’arrivée !`:`${NAMES[turn]} avance de ${dice} case${dice>1?'s':''}.`;setLogs(l=>[line,...l].slice(0,5));setMessage(line);if(result.captured)tone(180,.3);if(result.finished)tone(880,.35);if(result.winner){setWinner(turn);setPhase('won');tone(1046,.7);}else if(dice===6||result.captured||result.finished){setPhase('roll');setMessage(line+' Rejouez !');}else nextTurn();lock.current=false;}
 useEffect(()=>{if(!computer||modal||winner!==null)return;const timer=setTimeout(()=>{if(phase==='roll')void roll();else if(phase==='choose'){const choices=legal(tokens,turn,dice);choices.sort((a:number,b:number)=>{const score=(i:number)=>{const r=advance(tokens,turn,i,dice);return (r.winner?10000:0)+(r.finished?500:0)+r.captured*200+(tokens[turn][i]===-1?70:tokens[turn][i]);};return score(b)-score(a)});if(choices.length)void move(choices[0]);}},fast?350:1000);return()=>clearTimeout(timer);},[computer,phase,turn,tokens,modal,winner,fast]);
 function start(){setMode(draftMode);epoch.current++;lock.current=false;setTokens(fresh());setActive(count===2?[0,2]:count===3?[0,1,2]:[0,1,2,3]);setTurn(0);setDice(1);setSixes(0);setMoves(0);setLogs([]);setWinner(null);setRolling(false);setPhase('roll');setMessage('À vous de lancer le dé !');setModal('');}
 const playerName=(c:number)=>mode==='bot'?(c===0?'Vous':`Ordinateur ${active.filter(v=>v!==0).indexOf(c)+1}`):`Joueur ${active.indexOf(c)+1}`;
 function player(c:number){const enabled=active.includes(c);return <div className={`player ${turn===c&&enabled?'current':''} ${!enabled?'absent':''}`} style={{'--player':COLORS[c]} as React.CSSProperties}><div className="avatar">{mode==='bot'&&c!==0?<Bot size={24}/>:<Users size={23}/>}</div><div><strong>{enabled?playerName(c):'Place libre'}</strong><span>{enabled?<><i/>{NAMES[c]} <b>·</b> {tokens[c].filter(v=>v===56).length}/4 arrivés</>:'Joueur inactif'}</span></div>{enabled&&turn===c&&<span className="turn-tag">À jouer</span>}</div>}
 return <main><header><a className="brand" href="./"><span className="brand-icon"><Crown/></span><span>LUDO <b>ROYAL</b><small>LE PLAISIR DE JOUER ENSEMBLE</small></span></a><div className="header-right"><span className="local-badge"><i/> Jeu local</span><button className="icon-button" aria-label={sound?'Couper le son':'Activer le son'} onClick={()=>{setSound(!sound);if(!sound){try{audio.current??=new AudioContext();void audio.current.resume()}catch{}}}}>{sound?<Volume2 size={20}/>:<VolumeX size={20}/>}</button><button className="icon-button" aria-label="Réglages" onClick={()=>setModal('settings')}><Settings2 size={20}/></button></div></header>
 <div className="intro"><div><div className="eyebrow"><span/> LE GRAND CLASSIQUE</div><h1>Un dé. Quatre couleurs.<br/><em>À vous de jouer.</em></h1></div><button className="rules-link" onClick={()=>setModal('rules')}><HelpCircle size={18}/> Comment jouer</button></div>
 <div className="game-layout"><section className="arena" aria-label="Plateau de Ludo"><div className="players-row">{player(0)}{player(1)}</div><div className="board-frame"><div className="board"><svg viewBox="0 0 600 600" aria-hidden="true"><defs>{COLORS.map((c,i)=><linearGradient key={i} id={`color${i}`} x2="0.8" y2="1"><stop stopColor={c}/><stop offset="1" stopColor={['#c93638','#188d60','#dfaa2e','#286bc0'][i]}/></linearGradient>)}</defs><rect width="600" height="600" fill="#fffdf5"/>{[[0,0],[360,0],[360,360],[0,360]].map(([x,y],i)=><g key={i}><rect x={x} y={y} width="240" height="240" fill={`url(#color${i})`}/><rect x={x+33} y={y+33} width="174" height="174" rx="25" fill="#fffdf5" stroke="#ffffff55" strokeWidth="8"/>{[[80,80],[160,80],[80,160],[160,160]].map(([cx,cy],j)=><circle key={j} cx={x+cx} cy={y+cy} r="25" fill={COLORS[i]} fillOpacity=".13" stroke={COLORS[i]} strokeOpacity=".45" strokeWidth="2"/>)}</g>)}{PATH.map(([r,c]:number[],i:number)=><g key={i}><rect x={c*40} y={r*40} width="40" height="40" fill={i%13===0?COLORS[Math.floor(i/13)]:'#fffdf5'} stroke="#d7d9cf" strokeWidth="1"/>{SAFE.includes(i)&&<text x={c*40+20} y={r*40+28} textAnchor="middle" fontSize="29" fill={i%13===0?'#ffffffbb':'#bbc0b1'}>☆</text>}</g>)}{HOME.map((cells:number[][],i:number)=>cells.slice(0,5).map(([r,c],j)=><rect key={`${i}-${j}`} x={c*40} y={r*40} width="40" height="40" fill={COLORS[i]} stroke="#ffffff66"/>))}{['240,240 300,300 240,360','240,240 360,240 300,300','360,240 360,360 300,300','240,360 300,300 360,360'].map((p,i)=><polygon key={i} points={p} fill={COLORS[i]}/>)}<circle cx="300" cy="300" r="18" fill="#fffdf5"/><path d="M289 294l5 5 6-8 6 8 5-5-3 13h-16z" fill="#d4a645"/></svg>
 {tokens.map((ps,c)=>active.includes(c)&&ps.map((p,i)=>{const [r,col]=coordinate(c,p,i);const same=ps.filter(v=>v===p).length;const stacked=p>=0&&same>1;const offset=stacked?(i-1.5)*5:0;return <button key={`${c}-${i}`} aria-label={`Pion ${NAMES[c]} ${i+1}${p===-1?', dans la base':p===56?', arrivé':''}`} disabled={computer||!options.includes(i)||turn!==c||modal!==''} className={`pawn color-${c} ${options.includes(i)&&turn===c&&!computer?'selectable':''} ${p===56?'finished':''}`} style={{left:`calc(${(col+.5)/15*100}% + ${offset}px)`,top:`calc(${(r+.5)/15*100}% + ${stacked?offset*.4:0}px)`,'--pawn':COLORS[c],zIndex:20+i} as React.CSSProperties} onClick={()=>void move(i)}><span className="pawn-head"/><span className="pawn-base"/>{p===56&&<span className="finish-check">✓</span>}</button>}))}</div></div><div className="players-row bottom">{player(3)}{player(2)}</div><div className="board-caption"><ShieldCheck size={15}/> Cases étoilées : vos pions sont à l’abri <span>•</span> {moves} coups joués</div></section>
 <aside><section className="turn-card" style={{'--player':COLORS[turn]} as React.CSSProperties}><div className="card-label"><span className="live-dot"/> PARTIE EN COURS <span>{active.length} joueurs</span></div><div className="turn-title"><span className="mini-pawn" style={{background:COLORS[turn]}}/ ><h2>{winner!==null?'Partie terminée':computer?`${playerName(turn)} joue`:'C’est '+(mode==='bot'?'votre tour':`au ${playerName(turn).toLowerCase()}`)}</h2></div><p className="message" role="status" aria-live="polite">{message}</p><div className="dice-stage"><span className="dice-orbit"/><button className={`dice ${rolling?'rolling':''}`} aria-label={`Dé : ${dice}. Lancer le dé`} disabled={computer||phase!=='roll'||!!modal||winner!==null} onClick={()=>void roll()}>{Array.from({length:9},(_,i)=><i key={i} className={DOTS[dice].includes(i)?'pip':''}/>)}</button></div><button className="primary-button" disabled={computer||phase!=='roll'||winner!==null} onClick={()=>void roll()}>{rolling?'Le dé roule…':computer?'L’ordinateur joue…':phase==='choose'?'Choisissez un pion':'Lancer le dé'}<ArrowRight size={19}/></button><div className="dice-hint">Un <b>6</b> pour sortir. Un <b>6</b> pour rejouer.</div></section>
 <section className="session-card"><div className="section-title"><h3>Votre partie</h3><span>CLASSIQUE</span></div><div className="session-line"><span><Users size={17}/> Joueurs</span><strong>{active.length} joueurs</strong></div><div className="session-line"><span><Bot size={17}/> Mode de jeu</span><strong>{mode==='bot'?'Contre l’ordinateur':'Entre amis'}</strong></div><div className="session-line"><span><Flag size={17}/> Objectif</span><strong>4 pions à l’arrivée</strong></div><button className="secondary-button" onClick={()=>setModal('new')}><RotateCcw size={16}/> Nouvelle partie</button></section>
 <section className="activity"><div className="section-title"><h3>Les derniers coups</h3><span className="activity-dot"/></div>{logs.length?logs.slice(0,3).map((l,i)=><p key={`${moves}-${i}`} className={i===0?'latest':''}><span/> {l}</p>):<p className="empty-activity">La partie commence. Bonne chance !</p>}</section><div className="tip"><Sparkles size={18}/><p>Un peu de chance.<br/><strong>Beaucoup de bons moments.</strong></p></div></aside></div>
 <footer><span><Crown size={14}/> LUDO ROYAL</span><p>Un classique à partager, encore et encore.</p><button onClick={()=>setModal('rules')}>Les règles du jeu <ArrowRight size={14}/></button></footer>
 {modal&&<div className="modal-overlay" onClick={()=>setModal('')}><section className="modal" role="dialog" aria-modal="true" aria-label={modal==='rules'?'Règles du jeu':modal==='settings'?'Réglages':'Nouvelle partie'} onClick={e=>e.stopPropagation()}><button className="close icon-button" aria-label="Fermer" onClick={()=>setModal('')}><X/></button><Crown className="modal-crown"/><h2>{modal==='rules'?'Les règles du jeu':modal==='settings'?'À votre façon':'On refait une partie ?'}</h2>{modal==='rules'?<><p>Faites rentrer vos quatre pions au centre avant vos adversaires.</p><ol><li>Obtenez un <b>6</b> pour sortir un pion de sa base.</li><li>Lancez le dé, puis cliquez sur un pion illuminé pour avancer.</li><li>Atterrissez sur un adversaire pour le renvoyer à sa base. Les cases étoilées protègent tous les pions.</li><li>Un 6, une capture ou une arrivée vous permet de rejouer. Trois 6 consécutifs terminent votre tour.</li><li>Atteignez l’arrivée avec le chiffre exact. Les pions peuvent se dépasser et se superposer, sans former de blocage.</li></ol><button className="primary-button" onClick={()=>setModal('')}>C’est parti <ArrowRight size={18}/></button></>:modal==='settings'?<><label className="setting">Effets sonores<input type="checkbox" checked={sound} onChange={e=>setSound(e.target.checked)}/></label><label className="setting">Animations rapides<input type="checkbox" checked={fast} onChange={e=>setFast(e.target.checked)}/></label><button className="primary-button" onClick={()=>setModal('')}>Reprendre la partie</button></>:<><p>Choisissez vos adversaires. La partie actuelle sera remplacée.</p><label className="field-label">Mode de jeu</label><div className="choice-row"><button className={draftMode==='bot'?'chosen':''} onClick={()=>setDraftMode('bot')}><Bot/> Ordinateur</button><button className={draftMode==='local'?'chosen':''} onClick={()=>setDraftMode('local')}><Users/> Entre amis</button></div><label className="field-label" htmlFor="players">Nombre de joueurs</label><select id="players" value={count} onChange={e=>setCount(+e.target.value)}><option value="2">2 joueurs</option><option value="3">3 joueurs</option><option value="4">4 joueurs</option></select><button className="primary-button" onClick={start}>Commencer la partie <ArrowRight size={18}/></button></>}</section></div>}
 {winner!==null&&!modal&&<div className="modal-overlay"><section className="modal victory" role="dialog" aria-modal="true" aria-label="Victoire"><Trophy size={64}/><div className="eyebrow">QUATRE PIONS, UNE VICTOIRE</div><h2>{playerName(winner)} {winner===0&&mode==='bot'?'avez':'a'} gagné !</h2><p>Les {NAMES[winner].toLowerCase()}s remportent la partie en {moves} coups.</p><button className="primary-button" onClick={()=>setModal('new')}>Rejouer <RotateCcw size={18}/></button></section></div>}
 </main>
}
